name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies (server)
      run: |
        cd backend
        npm install

    - name: Run server tests
      run: |
        cd backend
        npm test

    - name: Install dependencies (client)
      run: |
        cd frontend
        npm install

    - name: Run client tests
      run: |
        cd frontend
        npm test

    - name: Build Docker images
      run: docker-compose build

    # Uncomment this step to deploy to AWS
    # - name: Deploy to AWS
    #   if: success()
    #   run: |
    #     echo "Deployment logic here"
